<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://external.interfaces.ers.seamless.com/">
<soapenv:Header/>
<soapenv:Body>
<ext:linkSubReseller>
<!--Optional:-->
<context>
<!--Optional:-->
<channel>WSClient</channel>
<!--Optional:-->
<clientComment></clientComment>
<!--Optional:-->
<clientId>ERS</clientId>
<!--Optional:-->
<prepareOnly>false</prepareOnly>
<!--Optional:-->
<clientReference></clientReference>
<clientRequestTimeout>${clientRequestTimeout}</clientRequestTimeout>
<!--Optional:-->
<initiatorPrincipalId>
<!--Optional:-->
<id>${initiatorPrincipalId}</id>
<!--Optional:-->
<type>${initiatorPrincipalType}</type>
<!--Optional:-->
<userId>${initiatorPrincipalUserId}</userId>
</initiatorPrincipalId>
<!--Optional:-->
<password>${password}</password>
<!--Optional:-->
<transactionProperties>
<!--Zero or more repetitions:-->
<entry>
<!--Optional:-->
<key>?</key>
<!--Optional:-->
<value>?</value>
</entry>
</transactionProperties>
</context>
<!--Optional:-->
<parentResellerId>${parentResellerId}</parentResellerId>
<!--Optional:-->
<principalId>
<!--Optional:-->
<id>${targetPrincipalId}</id>
<!--Optional:-->
<type>${targetPrincipalType}</type>
<!--Optional:-->
<userId>${targetPrincipalUserId}</userId>
</principalId>
</ext:linkSubReseller>
</soapenv:Body>
</soapenv:Envelope>