<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://external.interfaces.ers.seamless.com/">
<soapenv:Header/>
<soapenv:Body>
<ext:requestPrincipalInformation>
<!--Optional:-->
<context>
<!--Optional:-->
<channel>WSClient</channel>
<!--Optional:-->
<clientComment>?</clientComment>
<!--Optional:-->
<clientId>ers-std</clientId>
<!--Optional:-->
<prepareOnly>false</prepareOnly>
<!--Optional:-->
<clientReference>?</clientReference>
<clientRequestTimeout>${clientRequestTimeout}</clientRequestTimeout>
<!--Optional:-->
<initiatorPrincipalId>
<!--Optional:-->
<id>${initiatorPrincipalId}</id>
<!--Optional:-->
<type>${initiatorPrincipalType}</type>
<!--Optional:-->
<userId>${initiatorPrincipalUserId}</userId>
</initiatorPrincipalId>
<!--Optional:-->
<password>${password}</password>
<!--Optional:-->
<transactionProperties>
<!--Zero or more repetitions:-->
<entry>
<!--Optional:-->
<key>?</key>
<!--Optional:-->
<value>?</value>
</entry>
</transactionProperties>
</context>
<!--Optional:-->
<principalId>
<!--Optional:-->
<id>${principalId}</id>
<!--Optional:-->
<type>${principalType}</type>
<!--Optional:-->
<userId>${principalUserId}</userId>
</principalId>
<nativeReslutCode>0</nativeReslutCode>
</ext:requestPrincipalInformation>
</soapenv:Body>
</soapenv:Envelope>