<soapenv:Envelope
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:ext="http://external.interfaces.ers.seamless.com/">
<soapenv:Header/>
<soapenv:Body>
<ext:requestTopup>
<context>
<channel>WSClient</channel>
<clientComment>?</clientComment>
<clientId>ERS</clientId>
<prepareOnly>?</prepareOnly>
<clientReference>?</clientReference>
<clientRequestTimeout>${clientRequestTimeout}</clientRequestTimeout>
<initiatorPrincipalId>
<id>${initiatorPrincipalId}</id>
<type>${initiatorPrincipalType}</type>
<userId>${initiatorPrincipalUserId}</userId>
</initiatorPrincipalId>
<password>${password}</password>
<transactionProperties>
<!--Zero or more repetitions:-->
<entry>
<key>${key}</key>
<value>${value}</value>
</entry>
</transactionProperties>
</context>
<senderPrincipalId>
<id>${senderPrincipalId}</id>
<type>${senderPrincipalType}</type>
<userId>${senderPrincipalUserId}</userId>
</senderPrincipalId>
<topupPrincipalId>
<id>${topupPrincipalId}</id>
<type>${topupPrincipalType}</type>
<userId>?</userId>
</topupPrincipalId>
<senderAccountSpecifier>
<accountId>${senderAccountId}</accountId>
<accountTypeId>${senderAccountTypeId}</accountTypeId>
</senderAccountSpecifier>
<topupAccountSpecifier>
<accountId>${topupAccountId}</accountId>
<accountTypeId>${topupAccountTypeId}</accountTypeId>
</topupAccountSpecifier>
<productId>${productId}</productId>
<amount>
<currency>${currency}</currency>
<value>${topupAmount}</value>
</amount>
</ext:requestTopup>
</soapenv:Body>
</soapenv:Envelope>