<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://external.interfaces.ers.seamless.com/">
<soapenv:Header/>
<soapenv:Body>
<ext:requestTransfer>
<context>
<channel>WSClient</channel>
<clientComment>?</clientComment>
<clientId>ERS</clientId>
<prepareOnly>false</prepareOnly>
<clientReference>?</clientReference>
<clientRequestTimeout>${clientRequestTimeout}</clientRequestTimeout>
<initiatorPrincipalId>
<id>${initiatorPrincipalId}</id>
<type>${initiatorPrincipalType}</type>
<userId>${initiatorPrincipalUserId}</userId>
</initiatorPrincipalId>
<password>${password}</password>
<transactionProperties>
<!--Zero or more repetitions:-->
<entry>
<!--Optional:-->
<key>?</key>
<!--Optional:-->
<value>?</value>
</entry>
</transactionProperties>
</context>
<senderPrincipalId>
<id>${senderPrincipalId}</id>
<type>${senderPrincipalType}</type>
<userId>${senderPrincipalUserId}</userId>
</senderPrincipalId>
<receiverPrincipalId>
<id>${receiverPrincipalId}</id>
<type>${receiverPrincipalType}</type>
<userId>${receiverPrincipalUserId}</userId>
</receiverPrincipalId>
<senderAccountSpecifier>
<accountId>${senderAccountId}</accountId>
<accountTypeId>${senderAccountTypeId}</accountTypeId>
</senderAccountSpecifier>
<receiverAccountSpecifier>
<accountId>${receiverAccountId}</accountId>
<accountTypeId>${receiverAccountTypeId}</accountTypeId>
</receiverAccountSpecifier>
<productId>${productId}</productId>
<amount>
<currency>${currency}</currency>
<value>${transferAmount}</value>
</amount>
</ext:requestTransfer>
</soapenv:Body>
</soapenv:Envelope>