<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://external.interfaces.ers.seamless.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <ext:updateReseller>
         <!--Optional:-->
         <context>
            <!--Optional:-->
            <channel>?</channel>
            <!--Optional:-->
            <clientComment>?</clientComment>
            <!--Optional:-->
            <clientId>?</clientId>
            <!--Optional:-->
            <prepareOnly>?</prepareOnly>
            <!--Optional:-->
            <clientReference>?</clientReference>
            <clientRequestTimeout>${clientRequestTimeout}</clientRequestTimeout>
            <!--Optional:-->
            <initiatorPrincipalId>
               <!--Optional:-->
               <id>${initiatorPrincipalId}</id>
               <!--Optional:-->
               <type>${initiatorPrincipalType}</type>
               <!--Optional:-->
               <userId>${initiatorPrincipalUserId}</userId>
            </initiatorPrincipalId>
            <!--Optional:-->
            <password>${password}</password>
            <!--Optional:-->
            <transactionProperties>
               <!--Zero or more repetitions:-->
               <entry>
                  <!--Optional:-->
                  <key>?</key>
                  <!--Optional:-->
                  <value>?</value>
               </entry>
            </transactionProperties>
         </context>
         <!--Optional:-->
         <targetReseller>
            <!--Optional:-->
            <principalId>
               <!--Optional:-->
               <id>${targetResellerPrincipalId}</id>
               <!--Optional:-->
               <type>${targetResellerPrincipalType}</type>
               <!--Optional:-->
               <userId>${targetResellerUserId}</userId>
            </principalId>
         </targetReseller>
         <!--Optional:-->
         <updateResellerProfile>
            <!--Optional:-->
            <resellerMsisdn>${resellerMsisdn}</resellerMsisdn>
            <!--Optional:-->
            <address>
               <!--Optional:-->
               <street>${street}</street>
               <!--Optional:-->
               <city>${city}</city>
               <!--Optional:-->
               <country>?</country>
               <!--Optional:-->
               <phone>?</phone>
               <!--Optional:-->
               <fax>?</fax>
               <!--Optional:-->
               <homepage>?</homepage>
               <!--Optional:-->
               <zip>${zip}</zip>
               <!--Optional:-->
               <email>${email}</email>
            </address>
            <!--Optional:-->
            <person>
               <!--Optional:-->
               <firstName>${firstName}</firstName>
               <!--Optional:-->
               <lastName>${lastName}</lastName>
               <!--Optional:-->
               <middleName>?</middleName>
            </person>
         </updateResellerProfile>
      </ext:updateReseller>
   </soapenv:Body>
</soapenv:Envelope>