<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<ns2:requestPrincipalInformationResponse xmlns:ns2="http://external.interfaces.ers.seamless.com/">
<return>
<ersReference>${ersReference}</ersReference>
<resultCode>0</resultCode>
<resultDescription>SUCCESS</resultDescription>
<requestedPrincipal>
<principalId>
<id>${principalId}</id>
<type>${principalType}</type>
</principalId>
<principalName>${principalName}</principalName>
<accounts>
<account>
<accountDescription>${accountDescription}</accountDescription>
<accountSpecifier>
<accountId>${accountId}</accountId>
<accountTypeId>${accountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${balance}</value>
</balance>
<creditLimit>
<currency>${currency}</currency>
<value>${creditLimit}</value>
</creditLimit>
</account>
</accounts>
<status>${accountStatus}</status>
<msisdn>${msisdn}</msisdn>
</requestedPrincipal>
<userId>${principalUserId}</userId>
</return>
</ns2:requestPrincipalInformationResponse>
</soap:Body>
</soap:Envelope>