<#--Should be formatted with new lines and tabs-->
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<ns2:requestTopupResponse xmlns:ns2="http://external.interfaces.ers.seamless.com/">
<return>
<ersReference>${ersReference}</ersReference>
<resultCode>0</resultCode>
<resultDescription>SUCCESS</resultDescription>
<requestedTopupAmount>
<currency>${currency}</currency>
<value>${topupAmount}</value>
</requestedTopupAmount>
<senderPrincipal>
<principalId>
<id>${senderPrincipalId}</id>
<type>${senderPrincipalType}</type>
</principalId>
<principalName>${principalName}</principalName>
<accounts>
<account>
<accountSpecifier>
<accountId>${senderAccountId}</accountId>
<accountTypeId>${senderAccountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${senderAvailableBalance}</value>
</balance>
<creditLimit>
<currency>${currency}</currency>
<value>${creditLimit}</value>
</creditLimit>
</account>
</accounts>
<status>${status}</status>
<msisdn>${senderMSISDN}</msisdn>
</senderPrincipal>
<topupAccountSpecifier>
<accountId>${topupAccountId}</accountId>
<accountTypeId>${topupAccountTypeId}</accountTypeId>
</topupAccountSpecifier>
<topupAmount>
<currency>${currency}</currency>
<value>${topupAmountConvertedToDouble}</value>
</topupAmount>
<topupPrincipal>
<principalId>
<id>${topupPrincipalId}</id>
<type>${topupPrincipalType}</type>
</principalId>
<principalName></principalName>
<accounts>
<account>
<accountSpecifier>
<accountId>${topupAccountId}</accountId>
<accountTypeId>${topupAccountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${receiverBalanceConvertedToDouble}</value>
</balance>
</account>
</accounts>
</topupPrincipal>
</return>
</ns2:requestTopupResponse>
</soap:Body>
</soap:Envelope>