<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<ns2:requestTransferResponse xmlns:ns2="http://external.interfaces.ers.seamless.com/">
<return>
<ersReference>${ersReference}</ersReference>
<resultCode>0</resultCode>
<resultDescription>SUCCESS</resultDescription>
<receivedAmount>
<currency>${currency}</currency>
<value>${transferAmountConvertedToDouble}</value>
</receivedAmount>
<receiverPrincipal>
<principalId>
<id>${receiverPrincipalId}</id>
<type>${receiverPrincipalType}</type>
</principalId>
<principalName>${receiverPrincipalName}</principalName>
<accounts>
<account>
<accountSpecifier>
<accountId>${receiverAccountId}</accountId>
<accountTypeId>${receiverAccountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${receiverAvailableBalance}</value>
</balance>
<creditLimit>
<currency>${currency}</currency>
<value>${receiverCreditLimit}</value>
</creditLimit>
</account>
</accounts>
<status>${receiverAccountStatus}</status>
<msisdn>${receiverMSISDN}</msisdn>
</receiverPrincipal>
<requestedTransferAmount>
<currency>${currency}</currency>
<value>${transferAmount}</value>
</requestedTransferAmount>
<senderPrincipal>
<principalId>
<id>${senderPrincipalId}</id>
<type>${senderPrincipalType}</type>
</principalId>
<principalName>${senderPrincipalName}</principalName>
<accounts>
<account>
<accountSpecifier>
<accountId>${senderAccountId}</accountId>
<accountTypeId>${senderAccountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${senderAvailableBalance}</value>
</balance>
<creditLimit>
<currency>${currency}</currency>
<value>${senderCreditLimit}</value>
</creditLimit>
</account>
</accounts>
<status>${senderAccountStatus}</status>
<msisdn>${senderMSISDN}</msisdn>
</senderPrincipal>
</return>
</ns2:requestTransferResponse>
</soap:Body>
</soap:Envelope>