<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<ns2:requestPurchaseResponse xmlns:ns2="http://external.interfaces.ers.seamless.com/">
<return>
<ersReference>${ersReference}</ersReference>
<resultCode>0</resultCode>
<resultDescription>You have transferred Voucher ${serialNo}, worth ${voucherValue} ${currency} to ${receiverPrincipalId}, Your remaining balance is ${senderAvailableBalance} ${currency}.</resultDescription>
<receiverPrincipal>
<principalId>
<id>${receiverPrincipalId}</id>
<type>${receiverPrincipalType}</type>
</principalId>
<principalName></principalName>
<accounts>
<account>
<accountSpecifier>
<accountId>${receiverAccountId}</accountId>
<accountTypeId>${receiverAccountTypeId}</accountTypeId>
</accountSpecifier>
<balance>
<currency>${currency}</currency>
<value>${receiverAvailableBalance}</value>
</balance>
</account>
</accounts>
</receiverPrincipal>
<purchasedProducts>
<productSpecifier>
<productId>${productId}</productId>
<productIdType>${productTypeId}</productIdType>
</productSpecifier>
<purchaseCount>${purchaseCount}</purchaseCount>
<productDetails>
<map>
<entry>
<key>SERIAL</key>
<value>${serialNo}</value>
</entry>
<entry>
<key>EXPIRY_DATE</key>
<value>${expiryDate}</value>
</entry>
<entry>
<key>PIN</key>
<value>${pin}</value>
</entry>
</map>
</productDetails>
</purchasedProducts>
</return>
</ns2:requestPurchaseResponse>
</soap:Body>
</soap:Envelope>